# Generated by Django 3.2 on 2023-01-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doll',
            old_name='category',
            new_name='dolltype',
        ),
    ]
